### ISSUE TITLE
need colored text feature

### ISSUE THREAD

**Issue by allaze-eroler** [MitchCroft/UnityEditorTweaks#1]
hello, could you please add a colored text feature because in some case, you can get this situation:

![image](https://user-images.githubusercontent.com/6775478/79991444-9c53bc80-84b2-11ea-851e-62000fa18769.png)

as you can see, the purple color mix hardly with the text color which turned it unreadable.

thank you!

**Comment by MitchCroft** [comment]
That's a good idea, I'll try to get that in as soon as I can

**Comment by MitchCroft** [comment]
I didn't do anything super fancy so it was a lot faster then I though it would be. Not the prettiest, but it works at least. Each option lets you override the text color that will be used. If multiple colors are allowed to be be applied to a single entry, the first overriding text color will be used.

![image](https://user-images.githubusercontent.com/12761677/80571246-9ffdbb00-8a3f-11ea-9a8a-9262d68a301d.png)

Let me know if that works for you :)

**Comment by allaze-eroler** [comment]
oops sorry for a late reply!

yes, i like this method, and it worked better than i though indeed!

once again, sorry for the delay ^^;
